import type { Metadata } from "next";
import { Prompt } from 'next/font/google'
import "./globals.css";
import styles from  "./layout.module.css"
import Aside from "./components/Aside";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const prompt = Prompt({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700']
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${prompt.className} ${styles.main} ` } >
        <Aside />
        {children}
      </body>
    </html>
  );
}
